### PR TITLE
Update for flake8 v3.6

### PR DESCRIPTION
**Pull request by ChrisKeefe**
Numerous minor updates for compliance with flake8 v3.6, as discussed in qiime2/qiime2#415

### CODE REVIEW

**Comment by thermokarst** [comment]
Hey @ChrisKeefe - can you fix up these merge conflicts?

**Comment by ChrisKeefe** [comment]
Fixed. Looks like CWL is a moving target. If this round doesn't merge before new conflicts are introduced, let's just close this PR. I can always look at it again later if necessary.

**Comment by thermokarst** [comment]
Thanks! No worries, this is generally how things go when multiple people are working on the same repo at the same time --- luckily tools like git keep us sorted out! 🎂

**Review by thermokarst — APPROVED** [review]
LGTM, thanks @ChrisKeefe!

**Pull request merged**
