### PR TITLE
Updating copyright & license year

### PR DESCRIPTION
**Pull request by lizgehret**
Adding copyright header to missing files & updating license year to include 2021

### CODE REVIEW

**Comment by Keegan-Evans** [comment]
Did you run flake8 on these?

**Comment by lizgehret** [comment]
@Keegan-Evans great catch, thank you! I did not - will run that on these PRs and then submit any needed changes.

**Comment by lizgehret** [comment]
Flake8 errors:

1. 
`./q2cwl/cli.py:17:25: F821 undefined name 'Status'
`

Line: 

`def echo_status(status: 'Status', quiet: bool = False):
`

2.
`./q2cwl/template.py:158:13: F841 local variable 'default' is assigned to but never used
`

Lines:

```
else:            
  default = spec.default
```

Leaving these as-is unless these pose issues with the code as it currently stands (but doesn't seem that way).

**Review by thermokarst — APPROVED** [review]
Woot! LGTM, thanks!

**Comment by thermokarst** [comment]
> Flake8 errors:

I'm good with leaving these as-is for now. Flake8 isn't part of this assignment, so getting that squared away is a "bonus" in my eyes. Thanks!

**Pull request merged**
